# 1. Bật STRICT cho toàn bộ namespace yas, trừ cổng 8090 ra cho Observability
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: yas-mtls
  namespace: yas
spec:
  selector:
    matchLabels:
      security.istio.io/tlsMode: istio
  mtls:
    mode: STRICT
  portLevelMtls:
    8090:
      mode: PERMISSIVE
---
# 2. Mở PERMISSIVE riêng cho storefront-bff để NGINX Ingress có thể giao tiếp
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: storefront-bff-ingress-mtls
  namespace: yas
spec:
  selector:
    matchLabels:
      app: storefront-bff
  mtls:
    mode: STRICT
  portLevelMtls:
    80:
      mode: PERMISSIVE
---
# 3. Mở PERMISSIVE riêng cho backoffice-bff để NGINX Ingress có thể giao tiếp
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: backoffice-bff-ingress-mtls
  namespace: yas
spec:
  selector:
    matchLabels:
      app: backoffice-bff
  mtls:
    mode: STRICT
  portLevelMtls:
    80:
      mode: PERMISSIVE
---
# 4. Mở PERMISSIVE riêng cho swagger-ui để NGINX Ingress có thể giao tiếp
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: swagger-ui-ingress-mtls
  namespace: yas
spec:
  selector:
    matchLabels:
      app: swagger-ui
  mtls:
    mode: STRICT
  portLevelMtls:
    80:
      mode: PERMISSIVE
